title: Xuwei Tie's Homepage
page-top-title: Xuwei Tie
top-section-bg-text: Quiet life or blaze of glory
home-subtitle: Xuwei Tie&ensp;|&ensp;铁旭玮
copyright-text: '&copy; Xuwei Tie 2023-2025. All Rights Reserved.'
